### ISSUE TITLE
Web essentials

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/scottish-lidar#12]
- [x] Cookie consent
  - [x] Static content pages
  - [x] Google tag mgr
  - [x] Mobile/ tablet
  - [x] Meta / title / description tags
  - [x] Map events in Google analytics
  - [x] Robots.txt and sitemap.xml
  - [x] 404 page

**Comment by jonparsonsjncc** [comment]
Hi @PeteMontgomery 
could you add this tag manager code please to all pages
see attached[https://app.zenhub.com/files/197416226/0b2e674e-ce06-483b-8e48-3a07f766063c/download](https://app.zenhub.com/files/197416226/0b2e674e-ce06-483b-8e48-3a07f766063c/download)

**Comment by jonparsonsjncc** [comment]
Hi @PeteMontgomery 
please try this one
[https://app.zenhub.com/files/197416226/12c831f2-d9b4-431a-b029-08f288ae9ab3/download](https://app.zenhub.com/files/197416226/12c831f2-d9b4-431a-b029-08f288ae9ab3/download)

**Comment by PeteMontgomery** [comment]
Done
