### ISSUE TITLE
Aggregate outline layer

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/scottish-lidar#17]
We need an "aggregate layer" that shows the outline extent of all the data products we have. This should just be a single-pixel outline, in some bright colour, which will be shown as the lowest layer on the Leaflet map. So if you're looking at lidar/phase-1/dtm you won't see this outline as it will be hidden by the visualisation, but you will see the outline for phase-2 and any other datasets added in the future. @mattdebont any help appreciated! :-) Not sure whether this can be done dynamically in Geoserver with layer groups (that would be ideal) or whether it needs to be an offline processing thing.

**Comment by mattdebont** [comment]
Should be able to create something, but there are issues around creating this when the data streams don't cover the same area, as the outline only helps if all data is there

**Comment by mattdebont** [comment]
Needs to be a seperate data product, not entirely sure its a useful thing to do as if we are going to base the coverage we have on a vector we end up with a very complex polygon that will need simplifying as well, but how you deal with one pixel holes, etc...

**Comment by jonparsonsjncc** [comment]
re opening this ticket as we need to update the aggregate layer to follow a specific colour range

“the colour palette for the map and WMS isn’t colourblind friendly, it would be better to use a perceptually-uniform sequential palettes like the viridis family”

@mattdebont could you push this on to the staging site for the client to see please

**Comment by mattdebont** [comment]
I think this is the wrong ticket for this work, this ticket is about the aggregate layer not the individual layer styles, which the the viridis colour range would fall under

**Comment by jonparsonsjncc** [comment]
OK closing and will create a new ticket
