### ISSUE TITLE
Metadata updates

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/scottish-lidar#24]
A few out of date references on the contribute page of the remote sensing portal. The SSDI is now referred to as SpatialData.gov.scot. The guidance references are pointing to an old version of the portal. They are now using version 3.10.x of Geonetwork. If you use the prefix https://scottish-sdi-metadata-portal.readthedocs.io/en/latest/ before each of the sections it should always default to the most current.

**Comment by CathyJinJNCC** [comment]
@LynnHeeley I've pushed those changes to beta, can you confirm they're okay then I'll merge to live? https://beta-scottish-remote-sensing-portal.jncc.gov.uk/contribute

Ignore the map on the beta site, I think Pete was testing something. :)

**Comment by CathyJinJNCC** [comment]
Deployed to live
